// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TestTaskUniversity.Models.DbContext;

namespace TestTaskUniversity.Migrations.UniversityDb
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20170905073959_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestTaskUniversity.Models.Course.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Hours")
                        .HasMaxLength(300);

                    b.Property<string>("Name")
                        .HasMaxLength(300);

                    b.Property<string>("Subject")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("TestTaskUniversity.Models.Course.StudentCourse", b =>
                {
                    b.Property<string>("StudentId");

                    b.Property<int>("CourseId");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourse");
                });

            modelBuilder.Entity("TestTaskUniversity.Models.Course.TeacherCourse", b =>
                {
                    b.Property<string>("TeacherId");

                    b.Property<int>("CourseId");

                    b.HasKey("TeacherId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("TeacherCourse");
                });

            modelBuilder.Entity("TestTaskUniversity.Models.Users.Student", b =>
                {
                    b.Property<string>("AppUserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Department")
                        .HasMaxLength(300);

                    b.Property<string>("Direction")
                        .HasMaxLength(300);

                    b.HasKey("AppUserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("TestTaskUniversity.Models.Users.Teacher", b =>
                {
                    b.Property<string>("AppUserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Subject")
                        .HasMaxLength(300);

                    b.HasKey("AppUserId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("TestTaskUniversity.Models.Course.StudentCourse", b =>
                {
                    b.HasOne("TestTaskUniversity.Models.Course.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TestTaskUniversity.Models.Users.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TestTaskUniversity.Models.Course.TeacherCourse", b =>
                {
                    b.HasOne("TestTaskUniversity.Models.Course.Course", "Course")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TestTaskUniversity.Models.Users.Teacher", "Teacher")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
